#!/usr/bin/env python3
"""
Generate src/tokenizer/unicode_tables.h from Python's unicodedata.

The Qwen tokenizer needs two things std::regex and the C++ standard library
cannot provide:

  1. NFC normalization. It is ACTIVE and LOSSY -- decode(encode("café"))
     returns the precomposed form -- so skipping it produces different token ids
     on any text containing combining marks.
  2. The general categories L, M and N, for the pretokenizer regex
     [^\\r\\n\\p{L}\\p{N}]?[\\p{L}\\p{M}]+ etc.

Emitted as sorted range tables plus binary search, which is compact and fast
enough: the pretokenizer touches every codepoint of every prompt exactly once.

Usage: python3 tools/gen_unicode_tables.py > src/tokenizer/unicode_tables.h
"""
import sys, unicodedata

MAXCP = 0x110000

def ranges(pred):
    out, start = [], None
    for cp in range(MAXCP):
        if pred(cp):
            if start is None: start = cp
        else:
            if start is not None: out.append((start, cp-1)); start = None
    if start is not None: out.append((start, MAXCP-1))
    return out

def cat_pred(prefix):
    def f(cp):
        try: return unicodedata.category(chr(cp)).startswith(prefix)
        except ValueError: return False
    return f

def emit_ranges(name, rs, out):
    out.append(f"// {len(rs)} ranges")
    out.append(f"static const uint32_t {name}[][2] = {{")
    line = "  "
    for a, b in rs:
        piece = "{0x%X,0x%X}," % (a, b)
        if len(line) + len(piece) > 96:
            out.append(line); line = "  "
        line += piece
    if line.strip(): out.append(line)
    out.append("};")
    out.append(f"static const size_t {name}_N = sizeof({name})/sizeof({name}[0]);")
    out.append("")

def main():
    out = []
    out.append("// GENERATED by tools/gen_unicode_tables.py -- do not edit by hand.")
    out.append(f"// Unicode data version: {unicodedata.unidata_version}")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append("#include <cstddef>")
    out.append("")
    out.append("namespace qwen::uni {")
    out.append("")

    # ---- general categories -------------------------------------------
    for name, prefix in (("kLetter", "L"), ("kMark", "M"), ("kNumber", "N")):
        emit_ranges(name, ranges(cat_pred(prefix)), out)

    # ---- Unicode White_Space ------------------------------------------
    # Rust's regex crate (which HF tokenizers uses) makes \\s Unicode-aware, so it
    # is the White_Space property, NOT Python's str.isspace(): the latter also
    # returns true for U+001C..U+001F, which are NOT White_Space. Listed
    # explicitly because the set is small, stable, and getting it wrong changes
    # tokenization of every prompt containing NBSP or an ideographic space.
    WS = [(0x0009,0x000D),(0x0020,0x0020),(0x0085,0x0085),(0x00A0,0x00A0),
          (0x1680,0x1680),(0x2000,0x200A),(0x2028,0x2029),(0x202F,0x202F),
          (0x205F,0x205F),(0x3000,0x3000)]
    emit_ranges("kWhitespace", WS, out)

    # ---- canonical combining class ------------------------------------
    ccc = [(cp, unicodedata.combining(chr(cp))) for cp in range(MAXCP)]
    ccc = [(cp, c) for cp, c in ccc if c]
    out.append(f"// canonical combining class, {len(ccc)} nonzero entries")
    out.append("struct CccEntry { uint32_t cp; uint8_t ccc; };")
    out.append("static const CccEntry kCcc[] = {")
    line = "  "
    for cp, c in ccc:
        piece = "{0x%X,%d}," % (cp, c)
        if len(line) + len(piece) > 96:
            out.append(line); line = "  "
        line += piece
    if line.strip(): out.append(line)
    out.append("};")
    out.append("static const size_t kCcc_N = sizeof(kCcc)/sizeof(kCcc[0]);")
    out.append("")

    # ---- canonical decomposition (single-step, non-Hangul) -------------
    # Hangul is handled algorithmically in the header; excluding it here keeps
    # the table an order of magnitude smaller.
    HANGUL_S, HANGUL_N = 0xAC00, 11172
    decomp = []
    for cp in range(MAXCP):
        if HANGUL_S <= cp < HANGUL_S + HANGUL_N: continue
        ch = chr(cp)
        d = unicodedata.decomposition(ch)
        if not d or d.startswith("<"): continue     # canonical only, no compat
        parts = [int(x, 16) for x in d.split()]
        assert 1 <= len(parts) <= 2, (cp, parts)
        decomp.append((cp, parts))
    out.append(f"// canonical decomposition, single step, non-Hangul, {len(decomp)} entries")
    out.append("struct DecompEntry { uint32_t cp; uint32_t a; uint32_t b; };  // b==0 -> singleton")
    out.append("static const DecompEntry kDecomp[] = {")
    line = "  "
    for cp, parts in decomp:
        a = parts[0]; b = parts[1] if len(parts) > 1 else 0
        piece = "{0x%X,0x%X,0x%X}," % (cp, a, b)
        if len(line) + len(piece) > 96:
            out.append(line); line = "  "
        line += piece
    if line.strip(): out.append(line)
    out.append("};")
    out.append("static const size_t kDecomp_N = sizeof(kDecomp)/sizeof(kDecomp[0]);")
    out.append("")

    # ---- canonical composition (primary composites only) ---------------
    # A pair (a,b) composes to c iff c decomposes canonically to exactly (a,b),
    # c is not in the composition exclusion set, and a has ccc 0.
    # Derived empirically: normalize the pair and see whether it collapses.
    comp = []
    for cp, parts in decomp:
        if len(parts) != 2: continue
        a, b = parts
        if unicodedata.combining(chr(a)) != 0: continue      # non-starter base
        if unicodedata.normalize("NFC", chr(a) + chr(b)) != chr(cp): continue  # excluded
        comp.append((a, b, cp))
    comp.sort()
    out.append(f"// canonical composition pairs (exclusions already removed), {len(comp)} entries")
    out.append("struct CompEntry { uint32_t a; uint32_t b; uint32_t c; };")
    out.append("static const CompEntry kComp[] = {")
    line = "  "
    for a, b, c in comp:
        piece = "{0x%X,0x%X,0x%X}," % (a, b, c)
        if len(line) + len(piece) > 96:
            out.append(line); line = "  "
        line += piece
    if line.strip(): out.append(line)
    out.append("};")
    out.append("static const size_t kComp_N = sizeof(kComp)/sizeof(kComp[0]);")
    out.append("")
    out.append("}  // namespace qwen::uni")
    print("\n".join(out))

if __name__ == "__main__":
    main()
