#!/usr/bin/env python3
"""
Vendor the ggml quantisation lookup tables into src/gguf/ggml_tables.h.

The i-quants are codebook quants: a stored index selects an entry from a fixed
grid, so the grids are part of the FORMAT, not of llama.cpp. Rather than take a
source dependency on llama.cpp's tree, they are extracted once and committed --
the same thing tools/gen_unicode_tables.py does for Unicode.

Usage: python3 tools/gen_ggml_tables.py /path/to/llama.cpp/ggml/src/ggml-common.h
"""
import re, sys, os

WANT = ["kmask_iq2xs", "ksigns_iq2xs", "iq2xxs_grid", "iq2xs_grid", "iq2s_grid",
        "iq3xxs_grid", "iq3s_grid", "kvalues_iq4nl"]

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else \
        "/home/patrickd/qwen38-weights/llama.cpp/ggml/src/ggml-common.h"
    text = open(src).read()
    out = []
    out.append("// GENERATED by tools/gen_ggml_tables.py -- do not edit.")
    out.append("//")
    out.append("// ggml's quantisation lookup tables. The i-quants are CODEBOOK quants: the")
    out.append("// stored index selects a grid entry, so these tables are part of the file")
    out.append("// format itself and not an implementation detail of llama.cpp.")
    out.append("//")
    out.append("// Source: llama.cpp ggml/src/ggml-common.h (MIT).")
    out.append("#pragma once")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace qwen {")
    out.append("")
    found = {}
    for name in WANT:
        m = re.search(r"GGML_TABLE_BEGIN\((\w+),\s*" + name + r",\s*([\w/*+ ]+)\)(.*?)GGML_TABLE_END\(\)",
                      text, re.S)
        if not m:
            print("MISSING table", name, file=sys.stderr)
            sys.exit(1)
        ctype, count, body = m.group(1), m.group(2).strip(), m.group(3)
        vals = [v.strip() for v in body.replace("\n", " ").split(",") if v.strip()]
        found[name] = len(vals)
        out.append("// %s[%s], %s" % (name, count, ctype))
        out.append("static const %s %s[%d] = {" % (ctype, name, len(vals)))
        for i in range(0, len(vals), 8):
            out.append("    " + ", ".join(vals[i:i + 8]) + ",")
        out.append("};")
        out.append("")
    out.append("}  // namespace qwen")
    dst = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "src", "gguf", "ggml_tables.h")
    open(dst, "w").write("\n".join(out) + "\n")
    for k, v in found.items():
        print("  %-16s %d entries" % (k, v))
    print("wrote", dst, "%.1f KB" % (os.path.getsize(dst) / 1024))

if __name__ == "__main__":
    main()
